### ISSUE TITLE
Getting FileNotFoundError

### ISSUE THREAD

**Issue by Priyamanandjha** [siyuyuan/GET#1]
Getting FileNotFoundError: [Errno 2] No such file or directory: 'output_ultra-fine/model_epoch10/Prompt_IsA_Model.pth' when ran the main_self_paced.py file.

Full error:
Traceback (most recent call last):
  File "main_self_paced.py", line 201, in <module>
    main()
  File "main_self_paced.py", line 194, in main
    model.load_state_dict(torch.load(cfg.save_model_dic))
  File "C:\Users\02213R744\Anaconda3\envs\curriculam_env\lib\site-packages\torch\serialization.py", line 699, in load   
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\02213R744\Anaconda3\envs\curriculam_env\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\02213R744\Anaconda3\envs\curriculam_env\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'output_ultra-fine/model_epoch10/Prompt_IsA_Model.pth'

**Comment by Priyamanandjha** [comment]
worked after commenting line 194 in "main_self_paced.py"
